export type { IconResult, InputSize, Theme, ValueType } from './types'
export { isSVG } from './is-svg'
export { debounce, searchIcons } from './search'
export type { SearchIconsOptions } from './search'
export { browseCollection, browseCollections, pickRandomPrefix } from './browse'
export type { BrowseCollectionOptions } from './browse'
export { DEFAULT_BROWSABLE_PREFIXES, DEFAULT_ICONIFY_API_BASE } from './constants'
export { isIconSelected, toggleIconSelection } from './selection'
export type { ToggleSelectionOptions } from './selection'
export { getSanitizedSvgFromCache, setSanitizedSvgInCache } from './sanitize-cache'
export { resolveIconSvgValue } from './resolve-svg'
export type { IconifyBuildResult, IconifyLoaders } from './resolve-svg'
